#config_version=5

mode:
  priority: 500
  start_events: start_high_score # , game_ending
  use_wait_queue: true

high_score:
  _overwrite: true
  enter_initials_timeout: 60
  award_slide_display_time: 5s
  # define your high score categories and the awards
  categories: !!omap
    - score:
        - GRAND CHAMPION
        - HIGH SCORE 1
        - HIGH SCORE 2
        - HIGH SCORE 3
        - HIGH SCORE 4

  # set the defaults
  defaults:
    score:
      - CUP: 69000
      - MUG: 60000
      - SEM: 50000
      - DBM: 40000
      - BBC: 600

###############################################################################################
#                                  SOUND PLAYER                                               #
###############################################################################################

sound_player:
  high_score_enter_initials:
    attract:
      mode_end_action: stop
  s_left_flipper_active: dropTarget
  s_right_flipper_active: dropTarget
  s_start_active: spin
  high_score_award_display:
    specialAward:
      action: play
    attract:
      action: stop

###############################################################################################
#                                  SLIDE PLAYER                                               #
###############################################################################################
slide_player:
  _overwrite: true
  high_score_enter_initials:
    high_score_enter_initials:
      target: middle
  high_score_award_display:
    high_score_award_display:
      target: middle
  mode_high_score_started:
    topper_slide:
      target: upper
    hs_base_slide:
      target: lower

###############################################################################################
#                                        SLIDES                                               #
###############################################################################################

slides:
  _overwrite: true
  high_score_enter_initials:
    - type: image
      image: red_backdrop
    - type: text
      font_size: 50
      font_name: Aafia
      color: black
      text: PLAYER (player_num)
      z: 100
      y: 400
    - type: text
      font_size: 50
      font_name: Aafia
      text: (award)
      color: black
      z: 100
      y: 200
    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      font_name: Aafia
      font_size: 100
      max_chars: 3
      color: yellow
      y: 300
      z: 100
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.3s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.3s
            repeat: true
            easing: in_out_quint
      shift_left_event: s_left_flipper_active
      shift_right_event: s_right_flipper_active
      select_event: s_start_active
    - type: text
      text: '<       >'
      font_size: 50
      color: black
      font_name: Aafia
      y: 100
      z: 100
    - type: text
      text: ''
      key: high_score
      font_size: 100
      font_name: Aafia
      color: black
      y: 50
      z: 100
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.3s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.3s
            repeat: true
            easing: in_out_quint

  high_score_award_display:
    - type: image
      image: red_backdrop
    - type: text
      text: (player_name)
      font_size: 50
      font_name: Aafia
      color: black
      y: 200
      z: 100
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.05s
          - property: opacity
            value: 0
            duration: 0.05s
            repeat: true
    - type: text
      text: (award)
      font_size: 50
      font_name: Aafia
      color: black
      y: 300
      z: 100
    - type: text
      text: (value)
      y: 100
      z: 100
      font_size: 50
      font_name: Aafia
      color: black
      number_grouping: true
      min_digits: 2
