#config_version=5

mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true
high_score:
  _overwrite: true
  enter_initials_timeout: 60
  award_slide_display_time: 4s
  # define your high score categories and the awards
  categories: !!omap
    - score:
        - GRAND CHAMPION
        - HIGH SCORE 1
        - HIGH SCORE 2
        - HIGH SCORE 3
        - HIGH SCORE 4

  # set the defaults
  defaults:
    score:
      - CUP: 69000
      - MUG: 60000
      - SEM: 50000
      - DBM: 40000
      - BBC: 600

# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: true
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display
slides:
  _overwrite: true
  high_score_enter_initials:
    - type: text
      font_size: 18
      text: PLAYER (player_num)
      x: 105
      y: 90
    - type: text
      font_size: 18
      text: (award)
      x: 105
      y: 70
    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      font_size: 18
      max_chars: 3
      x: 105
      y: 20
      shift_left_event: s_left_flipper
      shift_right_event: s_right_flipper
      select_event: s_start
    - type: text
      text: '<       >'
      font_size: 18
      x: 105
      y: 20
    - type: text
      text: ''
      key: high_score
      font_size: 18
      x: 105
      y: 50
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.3s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.3s
            repeat: true
            easing: in_out_quint
  high_score_award_display:
    - type: text
      text: (player_name)
      font_size: 18
      anchor_y: middle
      anchor_x: middle
      x: middle
      y: middle
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.05s
          - property: opacity
            value: 0
            duration: 0.05s
            repeat: true
    - type: text
      text: (award)
      font_size: 18
      x: 105
      y: 110
    - type: text
      text: (value)
      x: 105
      y: 30
      font_size: 20
      number_grouping: true
      min_digits: 2