#config_version=5

mode:
  start_events: knock_out_hit
  priority: 140

variable_player:
  s_star_1_active:
    score:
      int: 500
      block: true
  s_star_2_active:
    score:
      int: 500
      block: true
  s_star_3_active:
    score:
      int: 500
      block: true

show_player:
  mode_knockOut_started: stars
