#config_version=5

mode:
  start_events: knock_out_hit #starts when the knockout target is hit
  priority: 140
  stop_events: timer_knockOutHurryUp_timer_complete

timers:
  knockOut_timer:
    direction: up
    start_value: 0
    end_value: 10
    tick_interval: 1S
    debug: true
    control_events:
      - action: start
        event: mode_knockOut_started
  knockOutHurryUp_timer:
    direction: up
    start_value: 0
    end_value: 5
    tick_interval: 1S
    debug: true
    control_events:
      - action: start
        event: timer_knockOut_timer_complete

variable_player:
  s_star_1_active:
    score: 450
  s_star_2_active:
    score: 450
  s_star_3_active:
    score: 450

shots: #these shots are only defined for this mode
  star1:
    switch: s_star_1
  star2:
    switch: s_star_2
  star3: #the outlane mode is started by star3_hit
    switch: s_star_3

shot_groups:
  leftStars: #if left stars is completed then the inlane mode starts
    shots: star1, star2
    reset_events: ball_drain

show_player:
  mode_knockOut_started: stars
  timer_knockOut_timer_complete:
    stars_flash: play
    stars: stop
