#config_version=5

mode:
  start_events:
    - ball_started
    - timer_knockOutHurryUp_timer_complete
  priority: 120
  stop_events: knock_out_hit

event_player:
  s_star_1_active: pay50
  s_star_2_active: pay50
  s_star_3_active: pay50
