#config_version=5
#Cuphead Attract Mode

show_player:
  mode_attract_started: # when the mode begins...
    attract_display_loop: # play the "attract_display_loop" with a...
      speed: 1 # speed of 1
    output1: # just to show that two light shows can be called and run together
      speed: 4
#    attract_light_show2:
#      speed: 3

sound_player: # plays the attract music
  mode_attract_started:
    attract:
      loops: -1 # loops the music indefintiely
      mode_end_action: stop
  request_to_start_game: startCallOuts # play the announcer voice when a player is added

track_player:
  videoOn: # if the event named "videoOn" is posted
    music:
      action: pause # pause the music by..
      fade: .25 sec # fading over .25 seconds
  videoOff: # if the enven "videoOff" is posted
    music:
      action: play # play the music again by..
      fade: .25 sec #fading in over .25 seconds

slides: # these are the attract video slides
  a_beppi:
    widgets:
    - type: video
      video: a_beppi
      z: 10
  a_cagney:
    widgets:
    - type: video
      video: a_cagney
      z: 10
  a_calla:
    widgets:
    - type: video
      video: a_calla
      z: 10
  a_capt:
    widgets:
    - type: video
      video: a_capt
      z: 10
  a_hilda:
    widgets:
    - type: video
      video: a_hilda
      z: 10
  a_ribbi:
    widgets:
    - type: video
      video: a_ribbi
      z: 10
  a_robot:
    widgets:
    - type: video
      video: a_robot
      z: 10
  a_root:
    widgets:
    - type: video
      video: a_root
      z: 10
  a_train:
    widgets:
    - type: video
      video: a_train
      z: 10
  a_wally:
    widgets:
    - type: video
      video: a_wally
      z: 10


videos: # the video names must be defined
  a_beppi:
    file: attr_beppi.mp4
    height: 600 # set the aspect ration
    width: 1080
  a_cagney:
    file: attr_cagney.mp4
    height: 600
    width: 1080
  a_calla:
    file: attr_calla.mp4
    height: 600
    width: 1080
  a_capt:
    file: attr_capt.mp4
    height: 600
    width: 1080
  a_hilda:
    file: attr_hilda.mp4
    height: 600
    width: 1080
  a_ribbi:
    file: attr_ribbi.mp4
    height: 600
    width: 1080
  a_robot:
    file: attr_robot.mp4
    height: 600
    width: 1080
  a_root:
    file: attr_root.mp4
    height: 600
    width: 1080
  a_train:
    file: attr_train.mp4
    height: 600
    width: 1080
  a_wally:
    file: attr_wally.mp4
    height: 600
    width: 1080

images: # images must be defined
  score:
    file: score.png
    height: 300
    width: 1080
  title_image:
    file: title.zip
  finger_image:
    file: finger.png
  start_backdrop_image:
    file: start_backdrop.png
  film:
    file: film.png

slide_player: # this slide player will
  mode_attract_started: # start these slides when the mode begins
    title_slide:
      target: middle # sets the destination display for the slides
    finger_slide:
      target: upper
    bottom_slide:
      target: lower
