#config_version=5
#Cuphead Attract Mode

show_player:
  mode_attract_started:
#    attract_display_loop:
#      speed: 1
    output1: # just to show that two light shows can be called and run together
      speed: 4
#    attract_light_show2:
#      speed: 3

sound_player: # plays the attract music
  mode_attract_started:
    attract:
      loops: -1 # loops the music indefintiely
      mode_end_action: stop
  request_to_start_game: startCallOuts

track_player:
  videoOn:
    music:
      action: pause
      fade: 1 sec
  videoOff:
    music:
      action: play
      fade: 1 sec


videos:
  a_beppi:
    file: attr_beppi.mp4
    height: 600
    width: 1060
  a_cagney:
    file: attr_cagney.mp4
    height: 600
    width: 1080
  a_calla:
    file: attr_calla.mp4
    height: 600
    width: 1060
  a_capt:
    file: attr_capt.mp4
    height: 600
    width: 1060
  a_hilda:
    file: attr_hilda.mp4
    height: 600
    width: 1060
  a_ribbi:
    file: attr_ribbi.mp4
    height: 600
    width: 1060
  a_robot:
    file: attr_robot.mp4
    height: 600
    width: 1060
  a_root:
    file: attr_root.mp4
    height: 600
    width: 1060
  a_train:
    file: attr_train.mp4
    height: 600
    width: 1080
  a_wally:
    file: attr_wally.mp4
    height: 600
    width: 1060

widgets:
  knockout_widget:
    - type: image
      image: knockout_image
      expire: 2s
      z: 10
  dash_widget:
    - type: image
      image: dash_image
      expire: 2s
      z: 10
      fps: 30
      anchor_x: left
      anchor_y: bottom
      x: left
      y: bottom + 150

images:
  score:
    file: score.png
    height: 300
    width: 1080
  title_image:
    file: title.zip
  finger_image:
    file: finger.png
  start_backdrop_image:
    file: start_backdrop.png

slide_player:
  mode_attract_started:
    title_slide:
      target: middle
    finger_slide:
      target: upper
    score_slide:
      target: lower
