#config_version=5
#Cuphead Attract Mode

show_player:
  mode_attract_started:
    attract_display_loop:
      speed: 1
    output1: # just to show that two light shows can be called and run together
      speed: 4
#    attract_light_show2:
#      speed: 3

sound_player: # plays the attract music
  mode_attract_started:
    attract:
      loops: -1 # loops the music indefintiely
      mode_end_action: stop
  request_to_start_game: startCallOuts

track_player:
  videoOn:
    music:
      action: pause
      fade: 1 sec
  videoOff:
    music:
      action: play
      fade: 1 sec

slides:
  90slide:
    widgets:
    - type: image
      image: reel90
      loops: 0
  01slide:
    widgets:
    - type: image
      image: reel01
      loops: 0
  12slide:
    widgets:
    - type: image
      image: reel12
      loops: 0
  23slide:
    widgets:
    - type: image
      image: reel23
      loops: 0
  34slide:
    widgets:
    - type: image
      image: reel34
      loops: 0
  45slide:
    widgets:
    - type: image
      image: reel45
      loops: 0
  56slide:
   widgets:
   - type: image
     image: reel56
     loops: 0
  67slide:
   widgets:
   - type: image
     image: reel67
     loops: 0
  78slide:
    widgets:
    - type: image
      image: reel78
      loops: 0
  89slide:
    widgets:
    - type: image
      image: reel89
      loops: 0

slide_player:
  sw_reel0_active:
     90slide:
       target: reel_display
  sw_reel1_active:
    01slide:
      target: reel_display
  sw_reel2_active:
    12slide:
      target: reel_display
  sw_reel3_active:
    23slide:
      target: reel_display
  sw_reel4_active:
    34slide:
      target: reel_display
  sw_reel5_active:
    45slide:
      target: reel_display
  sw_reel6_active:
    56slide:
      target: reel_display
  sw_reel7_active:
    67slide:
      target: reel_display
  sw_reel8_active:
    78slide:
      target: reel_display
  sw_reel9_active:
    89slide:
      target: reel_display

videos:
  playCHvideo:
    file: calla.mp4
    height: 600
    width: 1060
#    volume: .5
#    events_when_played: videoOn
#    events_when_stopped: videoOff
  calla:
    file: calla.mp4
    height: 600
    width: 1060
#    events_when_played: videoOn
#    events_when_stopped: videoOff
  capt:
    file: capt.mp4
    height: 600
    width: 1060
#    events_when_played: videoOn
#    events_when_stopped: videoOff
  hilda:
    file: hilda.mp4
    height: 600
    width: 1060
#    events_when_played: videoOn
#    events_when_stopped: videoOff
  peppi:
    file: peppi.mp4
    height: 600
    width: 1060
#    events_when_played: videoOn
#    events_when_stopped: videoOff
  ribbi:
    file: ribbi.mp4
    height: 600
    width: 1060
#    events_when_played: videoOn
#    events_when_stopped: videoOff
  robot:
    file: robot.mp4
    height: 600
    width: 1060
#    events_when_played: videoOn
#    events_when_stopped: videoOff
  root:
    file: root.mp4
    height: 600
    width: 1060
#    events_when_played: videoOn
#    events_when_stopped: videoOff
  wally:
    file: wally.mp4
    height: 600
    width: 1060
#    events_when_played: videoOn
#    events_when_stopped: videoOff

images:
#  backdrop:
#    file: backdrop_star.png
  reel:
    file: reelPNGs.zip
#  rotate:
#    file: cupheadbackdrop.zip
  logo:
    file: logo.png
    height: 280
    width: 1040
  reel01:
    file: 01.zip
  reel12:
    file: 12.zip
  reel23:
    file: 23.zip
  reel34:
    file: 34.zip
  reel45:
    file: 45.zip
  reel56:
    file: 56.zip
  reel67:
    file: 67.zip
  reel78:
    file: 78.zip
  reel89:
    file: 89.zip
  reel90:
    file: 90.zip


#  video_slide:
#    - type: video
#      video: playCHvideo
#      end_behavior: stop
#      control_events:
#        - event: mode_attract_started
#          action: play

#slide_player:
#  mode_attract_started: video_slide
