#config_version=5
#Cuphead Attract Mode

show_player:
  mode_attract_started:
    attract_display_loop:
      speed: 1
    attract_light_show: # just to show that two light shows can be called and run together
      speed: 4
    attract_light_show2:
      speed: 3

sound_player: # plays the attract music
  mode_attract_started:
    attract_music:
      loops: -1 # loops the music indefintiely
      mode_end_action: stop
