#config_version=5
#Cuphead Attract Mode

show_player:
  mode_attract_started:
    attract_display_loop:
      speed: 1
    output1: # just to show that two light shows can be called and run together
      speed: 4
#    attract_light_show2:
#      speed: 3

sound_player: # plays the attract music
  mode_attract_started:
    attract:
      loops: -1 # loops the music indefintiely
      mode_end_action: stop
  request_to_start_game: startCallOuts

track_player:
  videoOn:
    music:
      action: pause
      fade: 1 sec
  videoOff:
    music:
      action: play
      fade: 1 sec

videos:
  calla:
    file: calla.mp4
    height: 600
    width: 1060
  capt:
    file: capt.mp4
    height: 600
    width: 1060
  hilda:
    file: hilda.mp4
    height: 600
    width: 1060
  peppi:
    file: beppi.mp4
    height: 600
    width: 1060
  ribbi:
    file: ribbi.mp4
    height: 600
    width: 1060
  robot:
    file: robot.mp4
    height: 600
    width: 1060
  root:
    file: root.mp4
    height: 600
    width: 1060
  wally:
    file: wally.mp4
    height: 600
    width: 1060

widgets:
  knockout_widget:
    - type: image
      image: knockout_image
      expire: 2s
      z: 10


images:
  topper:
    file: topper.zip
  fast_run_image:
    file: topper2.zip
  score:
    file: score.png
    height: 300
    width: 1080
  knockout_image:
    file: knockout.png


slide_player:
  mode_attract_started:
    video_slide:
      target: middle
#    topper_slide:
#      target: upper
    score_slide:
      target: lower
