#config_version=5
#Cuphead Base Mode Config

mode:
  start_events: ball_starting
  priority: 100 # lowest pririty so other modes can take over

sounds: # difines that four songs that can be played during a ball
  cupMusic1:
    target: music
    loop: -1
    mode_end_action: stop
  cupMusic2:
    target: music
    loop: -1
    mode_end_action: stop
  cupMusic3:
    target: music
    loop: -1
    mode_end_action: stop
  cupMusic4:
    target: music
    loop: -1
    mode_end_action: stop

sound_pools:
  poolCupHeadBase:
    type: random_force_all # play a random song but don't play one a second time until all have been played
    sounds:
      - cupMusic1
      - cupMusic2
      - cupMusic3
      - cupMusic4

counters:
  bonus:
    count_events: drop_target_bank_cup_bank_down, drop_target_bank_mug_bank_down # each bank gets its own counter
    events_when_hit: bank_done # when each back is done the event "bank_done" is posted
    starting_count: 0
    count_complete_value: 10 # set to 10 becasue there are 10 bonus lights
    direction: up
    persist_state: false # does not keep its value from ball to ball
    disable_on_complete: true # once all ten bonus lights are lit, stop the counter
  spinner_rotations:
    count_events: s_spinner_active
    count_complete_value: 7
    starting_count: 0
    direction: up
    persist_state: false
    events_when_hit: advance_lane
    reset_on_complete: true
    disable_on_complete: false

show_player:
  mode_base_started: base_lighting 
  advance_lane{count==1}: 1_on
  advance_lane{count==2}: 2_on
  advance_lane{count==3}: 3_on
  advance_lane{count==4}: 4_on
  advance_lane{count==5}: 5_on
  advance_lane{count==6}: 6_on
  advance_lane{count==7}: 7_on
  bank_done{count==1}: 1000_on # if bank_done is posted and the count value is 1 then run the show 1000_on
  bank_done{count==2}: 2000_on
  bank_done{count==3}: 3000_on
  bank_done{count==4}: 4000_on
  bank_done{count==5}: 5000_on
  bank_done{count==6}: 6000_on
  bank_done{count==7}: 7000_on
  bank_done{count==8}: 8000_on
  bank_done{count==9}: 9000_on
  bank_done{count==10}: 10000_on

sound_player:
  mode_base_started: # when the mode starts...
    poolCupHeadBase: # select a song from the pool..
      loops: -1 # and loop it indefinitely
  ball_drain : # when the ball drains...
    poolCupHeadBase:
      action: stop # stop playing the music

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: Player (player)
        y: 10
        x: 10
        font_size: 30
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: Contracts (contracts)
        font_size: 25
        color: red
        y: 60%

shots:
  drain_hit:
    switch: s_trough1

variable_player:
  bonus:
    int: 1
    action: set
  s_popBumper_1_active:
    score: 100
  s_popBumper_2_active:
    score: 100
  s_popBumper_3_active:
    score: 100
  s_dt_C_active:
    score: 100
  s_dt_U_active:
    score: 100
  s_dt_P_active:
    score: 100
  s_dt_M_active:
    score: 100
  s_dt_U2_active:
    score: 100
  s_dt_G_active:
    score: 100
  drop_target_bank_cup_bank_down: # if the bank is dropped...
    contracts: 1 # increment the counter contracts by one
  drop_target_bank_mug_bank_down:
    contracts: 1
  mode_base_started: # when the mode starts...
    contracts:
      int: 0 # put 0...
      action: set # into contracts
  s_midRight_active:
    score: 50
  s_perdition_active:
    score: 100
  s_dtSling_L_active:
    score: 10
  s_dtSling_R_active:
    score: 10
  s_sling_L_active:
    score: 10
  s_sling_R_active:
    score: 10
  s_standUp_1_active:
    score: 10
  s_standUp_2_active:
    score: 10
  s_standUp_3_active:
    score: 10
  s_standUp_R_active:
    score: 1000
  s_spinner_active:
    spinner_rotations: 1
    score: 10
