#config_version=5
#Cuphead Base Mode Config

mode:
  start_events: ball_starting
  priority: 100

sounds:
  cupMusic1:
    target: music
    loop: -1
    mode_end_action: stop
  cupMusic2:
    target: music
    loop: -1
    mode_end_action: stop
  cupMusic3:
    target: music
    loop: -1
    mode_end_action: stop
  cupMusic4:
    target: music
    loop: -1
    mode_end_action: stop

sound_pools:
  poolCupHeadBase:
    type: random_force_all
    sounds:
      - cupMusic1
      - cupMusic2
      - cupMusic3
      - cupMusic4

counters:
  bonus:
    count_events: drop_target_bank_cup_bank_down, drop_target_bank_mug_bank_down
    events_when_hit: bank_done
    starting_count: 0
    count_complete_value: 10
    direction: up
    persist_state: false
    disable_on_complete: true

show_player:
  mode_base_started:
    base_lighting:
      speed: 1
  bank_done{count==1}:
    1000_on:
      show_tokens:
  bank_done{count==2}:
    2000_on:
      show_tokens:
  bank_done{count==3}:
    3000_on:
      show_tokens:
  bank_done{count==4}:
    4000_on:
      show_tokens:
  bank_done{count==5}:
    5000_on:
      show_tokens:
  bank_done{count==6}:
    6000_on:
      show_tokens:
  bank_done{count==7}:
    7000_on:
      show_tokens:
  bank_done{count==8}:
    8000_on:
      show_tokens:
  bank_done{count==9}:
    9000_on:
      show_tokens:
  bank_done{count==10}:
    10000_on:
      show_tokens:

sound_player:
  mode_base_started:
    poolCupHeadBase:
      loops: -1
  ball_ending:
    poolCupHeadBase:
      action: stop

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: Player (player)
        y: 10
        x: 10
        font_size: 30
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: Contracts (contracts)
        font_size: 25
        color: red
        y: 60%

variable_player:
  bonus:
    int: 1
    action: set
  s_popBumper_1_active:
    score: bonus
  s_popBumper_2_active:
    score: 10
  s_popBumper_3_active:
    score: 10
  s_dt_C_active:
    score: 100
  s_dt_U_active:
    score: 100
  s_dt_P_active:
    score: 100
  s_dt_M_active:
    score: 100
  s_dt_U2_active:
    score: 100
  s_dt_G_active:
    score: 100
  drop_target_bank_cup_bank_down:
    contracts: 1
  drop_target_bank_mug_bank_down:
    contracts: 1
  mode_base_started:
    contracts:
      int: 0
      action: set
  s_midRight_active:
    score: 50
  s_perdition_active:
    score: 100
  s_dtSling_L_active:
    score: 10
  s_dtSling_R_active:
    score: 10
  s_sling_L_active:
    score: 10
  s_sling_R_active:
    score: 10
  s_standUp_1_active:
    score: 10
  s_standUp_2_active:
    score: 10
  s_standUp_3_active:
    score: 10
  s_standUp_R_active:
    score: 1000


#widgets:
#  contracts_banner:



#widget_player:
#  mode_soulLanes_started: contracts_banner
