#config_version=5

mode:
  start_events: mode_multiball_ready_started   # a mode that gets the machine ready to payout multiball if the devil bumper is hit
  stop_events: devil_bumper_hit, ball_ended   # end if mutiball is achieved or 2nd ball drained


queue_relay_player:
  ball_ending:     # if multiball has failed because of a ball drain prior to hitting the "devil bumper"...
    post: eject_bd_perdition_kicker    # eject the captured ball and...
    wait_for: balldevice_bd_trough_ball_count_changed{device.ball_devices.bd_trough.balls==2}    # wait for it to drain

sound_player:
  eject_bd_perdition_kicker: perditionkicker
