#config_version=5

mode:
  start_events: advance_perdition{count == 3}   # a mode that gets the machine ready to payout multiball if the devil bumper is hit
  priority: 1000
  use_wait_queue: true
  stop_events: devil_bumper, balldevice_bd_trough_ball_count_changed{device.ball_devices.bd_trough.balls == 2}   # end if mutiball is achieved or 2nd ball drained


queue_relay_player:
  ball_ending:     # if multiball has failed because of a ball drain prior to hitting the "devil bumper"...
    post: eject_bd_perdition_kicker   # eject the captured ball and...
    wait_for: balldevice_bd_trough_ball_count_changed{device.ball_devices.bd_trough.balls == 2}    # wait for it to drain

sound_player:
  eject_bd_perdition_kicker: perditionkicker

#event_player:
#  eject_bd_perdition_kicker: advance_perdition
