#config_version=5
mode:
  start_events: start_dashLit
  stop_events: dash_complete
  priority: 130

shots:
  dash_L:
    switch: s_dash_L
  dash_R:
    switch: s_dash_R

variable_player:
  dash_L_hit:
    score:
      int: 500
      block: true
  dash_R_hit:
    score: 500

event_player:
  dash_L_hit:
    dash_complete
  dash_R_hit:
    dash_complete

show_player:
  mode_dashLit_started:
    dashOn:
      show_tokens:
        lights: dash
