#config_version=5
mode:
  start_events: start_dashLit
  priority: 130

shots:
  dash_L:
    switch: s_dash_L
  dash_R:
    switch: s_dash_R

shot_groups:
  dash_lit:
    shots: dash_L, dash_R
    reset_events:
      dash_complete

variable_player:
  dash_complete:
    score: 500

show_player:
  dash_complete:
    dashOff:
      show_tokens:
        lights: dash
