#config_version=5
mode:
  start_events: standUps_complete
  stop_events: dash_complete
  priority: 130

shots:
  dash_L:
    switch: s_dash_L
  dash_R:
    switch: s_dash_R

event_player:
  dash_L_hit:
    - dash_complete
    - pay500
  dash_R_hit:
    - dash_complete
    - pay500

variable_player:
  s_standUp_1_active:
    score: 100
  s_standUp_2_active:
    score: 100
  s_standUp_3_active:
    score: 100

show_player:
  mode_dashLit_started:
    dashOn:
      show_tokens:
        lights: dash
    flash_green:
      loops: 4
      speed: 6
      show_tokens:
        lights: standUp

sound_player:
  dash_L_hit: dashLit
  dash_R_hit: dashLit
