#config_version=5
mode:
  start_events: standUps_complete
  stop_events: dash_complete
  priority: 130

shots:
  dash_L:
    switch: s_dash_L
  dash_R:
    switch: s_dash_R

variable_player:
  dash_L_hit:
    score: 500
  dash_R_hit:
    score: 500

event_player:
  dash_L_hit:
    dash_complete
  dash_R_hit:
    dash_complete

show_player:
  mode_dashLit_started:
    dashOn:
      show_tokens:
        lights: dash
    flash_green:
      loops: 4
      speed: 6
      show_tokens:
        lights: standUp

sound_player:
  dash_L_hit: dashLit
  dash_R_hit: dashLit
