#config_version=5

mode:
  start_events: rightStar_complete
  priority: 150
  stop_events: ball_drain, outLanes_complete

shots:
  outLaneL:
    switch: s_outLane_L
    show_tokens:
      light: l_outLane_L
    profile: outLaneL
  outLaneR:
    switch: s_outLane_R
    show_tokens:
      light: l_outLane_R
    profile: outLaneR


shot_groups:
  outLanes:
    shots: outLaneL, outLaneR
    reset_events: mode_outLanes_end

shot_profiles:
  outLaneL:
    states:
      - name: lit
        show: outLaneLon
      - name: unlit
        show: off
    loop: false
  outLaneR:
    states:
      - name: lit
        show: outLaneRon
      - name: unlit
        show: off
    loop: false

event_player:
    outLaneL_outLanes_unlit_hit: pay100
    outLaneR_outLanes_unlit_hit: pay100
    outLaneL_outLanes_lit_hit: pay1000
    outLaneR_outLanes_lit_hit: pay1000
