#config_version=5

# This is a mode that continuously drops the perdition post and tries to clear the perdition lane during a failed multiball

mode:
  start_events: multiballFail # start with achieving the multiball
  stop_events:  balldevice_bd_trough_ball_count_changed{device.ball_devices.bd_trough.balls == 2}  # end when both balls drain
  priority: 240
  restart_on_next_ball: true

timers:
  settleFail_timer:
    direction: down
    start_value: 4
    end_value: 0
    tick_interval: 100ms
    debug: true
    control_events:
      - action: start
        event: s_perdition_kicker_active.2
      - action: restart
        event: s_perdition_kicker_active.3

###############################################################################################
#                                      PLAYERS                                                #
###############################################################################################

variable_player:
  s_perdition_kicker_active:
    perdition_value:
      int: 0
      action: set
    advance_perdition_value:
      int: 0
      action: set

event_player:
  s_perdition_kicker_active: clearLane

coil_player:
  clearLane: c_perdition_post_down
  timer_settle_timer_complete: c_perdition_kicker

show_player:
  s_perdition_kicker_active:
    perdition0: play
    perdition1on: stop
    perdition2on: stop
    perdition3On: stop
