#config_version=5

mode:
  start_events:
    leftStars_complete # if the left stars are lit start this mode
  priority: 150
  stop_events:
    mode_inLanesLit_end # end this mode when both lanes have been lit and hit

shots:
  inLaneL:
    switch: s_inLane_L
    show_tokens:
      light: l_inLane_L
    profile: inLanes
  inLaneR:
    switch: s_inLane_R
    show_tokens:
      light: l_inLane_R
    profile: inLanes

variable_player:
  s_inLane_L_active: pay500
  s_inLane_R_active: pay500

shot_groups:
  inLanes:  # a shot group called inLanes that...
    shots: inLaneL, inLaneR  # consists of the left and right inlanes that...
    reset_events: mode_inLanesLit_end  # resets when the mode is complete

shot_profiles:
  inLanes:  # the shot inlanes has two states
    states:
      - name: lit  # starts with lit with the lights turned...
        show: on # on
      - name: unlit # and ends with unlit with the lights turned...
        show: off #  off
    loop: false # don't loop back to lit

#sound_player:
#  inLanes_lit_hit: inLanesLit # play this sound for this mode
