#config_version=5

mode:
  start_events: ball_starting, multiball_perdition_multiball_ball_lost # this will allow a second multiball opportunity after a ball drains
  stop_events:  eject_bd_perdition_kicker, ball_will_end # advance_perdition{count==3}, # the devil bumper is enabled after the third entry and will eject the locked ball and stop the mode
  priority: 200
  restart_on_next_ball: true

multiball_locks:
  perdition_lock:
    enable_events: advance_perdition{count==3} # counter for three entries to saucer
    balls_to_lock: 1
    lock_devices: bd_perdition_kicker # saucer in perdition lane
    reset_count_for_current_player_events: multiball_lock_perdition_lock_full

multiballs:
  perdition_multiball:
    ball_count: 2
    ball_locks: bd_perdition_kicker # this locks the ball and...
    start_events: startMBPost # this releases it (from the perdition mode)
    shoot_again: 2s

show_player:
  advance_perdition{count==3}:
    perdition_multiball_lights: # light show for multiball
      speed: 6

sound_player:
  startMBPost: perditionKick

shots: # this defines the shot...
  devil_bumper: # devil bumper as having the switch...
    switch: s_popBumper_2 # hit
