#config_version=5

#mode_settings:
#  display_delay_ms: 500
#  keep_multiplier: false
#  bonus_entries:
#    - event: 

mode_settings:
  bonus_entries:
    - event: bonusPayout
      score: 1000 * (current_player.bonus_multiplier + 1)
      player_score_entry: current_player.contracts 
      display_delay_ms: 500


widgets:
  bonusPayout_banner:
    type: text
    text: Bonus Payout (contracts)
    font_size: 25
    color: brown 
    y: 75%

widget_player:
  mode_bonus_started: bonusPayout_banner