#config_version=5

#mode_settings:
#  display_delay_ms: 500
#  keep_multiplier: false
#  bonus_entries:
#    - event: 

mode_settings:
  bonus_entries:
    - event: bonusPayout
      score: 1000 * (current_player.bonus_multiplier + 1) 
      player_score_entry: current_player.contracts

#timers:
#  bonusLight:
#    start_value: 3
#    end_value: 0 
#    direction: down
#    tick_interval: 500ms
#    debug: true
#    control_events:
#      - action: start
#        event: mode_bonus_started

#counters:
#  bonusStep:
#    count_events: s_popBumper_1_active
#    events_when_hit: light_done
#    starting_count: 3
#    count_complete_value: 0 
#    direction: down
#    persist_state: false
#    disable_on_complete: true

#show_player:
#  mode_bonus_started:
#    bonus_lighting:
#      speed: 1
#  light_done{count==1}:
#    1000_off:
#      show_tokens:
#        lights: l_bonus_1000
#  light_done{count==2}:
#    2000_off:
#      show_tokens:
#        lights: l_bonus_2000
#  light_done{count==3}:
#    3000_off:
#      show_tokens:
#        lights: l_bonus_3000
#  light_done{count==4}:
#    4000_off:
#      show_tokens:
#        lights: l_bonus_4000
#  light_done{count==5}:
#    5000_off:
#      show_tokens:
#        lights: l_bonus_5000
#  light_done{count==6}:
#    6000_off:
#      show_tokens:
#        lights: l_bonus_6000
#  light_done{count==7}:
#    7000_off:
#      show_tokens:
#        lights: l_bonus_7000
#  light_done{count==8}:
#    8000_off:
#      show_tokens:
#        lights: l_bonus_8000
#  light_done{count==9}:
#    9000_off:
#      show_tokens:
#        lights: l_bonus_9000
#  light_done{count==10}:
#    10000_off:
#      show_tokens:
#        lights: l_bonus_10000


widgets:
  bonusPayout_banner:
    type: text
    text: Bonus Payout (contracts)
    font_size: 25
    color: brown 
    y: 75%

widget_player:
  mode_bonus_started: bonusPayout_banner