#config_version=5

mode:
  stop_events: bonusDone

mode_settings:
  bonus_entries:
    - event: bonusPayout
      score: 0 #1000 * (current_player.bonus_multiplier + 1)
      player_score_entry: current_player.contracts

timers:
  bonusCountDown:
    start_value: current_player.contracts
    end_value: 0
    direction: down
    tick_interval: 500ms
    debug: true
    control_events:
      - action: start
        event: mode_bonus_started
      - action: stop
        event: bonusDone

event_player:
  timer_bonusCountDown-tick{current_player.contracts==0}:
    - bonusDone
  timer_bonusCountDown_tick{current_player.contracts>0}:
    - bonusPayout
    - light_done

variable_player:
  timer_bonusCountDown_tick{current_player.contracts>0}:
    contracts: -1
    score: 1000 * (current_player.bonus_multiplier + 1)


#counters:
#  bonusStep:
#    count_events: s_popBumper_1_active
#    events_when_hit: light_done
#    starting_count: 3
#    count_complete_value: 0
#    direction: down
#    persist_state: false
#    disable_on_complete: true

show_player:
#  mode_bonus_started:
#    bonus_lighting:
#      speed: 1
  light_done{current_player.contracts==0}:
    1000_off:
      show_tokens:
        lights: l_bonus_1000
  light_done{current_player.contracts==1}:
    2000_off:
      show_tokens:
        lights: l_bonus_2000
  light_done{current_player.contracts==2}:
    3000_off:
      show_tokens:
        lights: l_bonus_3000
  light_done{current_player.contracts==3}:
    4000_off:
      show_tokens:
        lights: l_bonus_4000
  light_done{current_player.contracts==4}:
    5000_off:
      show_tokens:
        lights: l_bonus_5000
  light_done{current_player.contracts==5}:
    6000_off:
      show_tokens:
        lights: l_bonus_6000
  light_done{current_player.contracts==6}:
    7000_off:
      show_tokens:
        lights: l_bonus_7000
  light_done{current_player.contracts==7}:
    8000_off:
      show_tokens:
        lights: l_bonus_8000
  light_done{current_player.contracts==8}:
    9000_off:
      show_tokens:
        lights: l_bonus_9000
  light_done{current_player.contracts==9}:
    10000_off:
      show_tokens:
        lights: l_bonus_10000

#slide_player:
#  mode_bonus_started:
#  bonusPayout: bonusPayout_slide


#slides:
#  bonusPayout_slide:
#    type: text
#    text: Bonus Payout (contracts)
#    font_size: 25
#    color: blue
#    y: 75%
