#config_version=5

mode:
  stop_events: bonusDone # end when the last bonus is paid out

mode_settings:
  bonus_entries:
    - event: bonusPayout
      score: 0 #1000 * (current_player.bonus_multiplier + 1)
      player_score_entry: current_player.contracts

timers:
  bonusCountDown:
    start_value: current_player.contracts # start with the current number of contracts collected and ...
    end_value: 0 # end at zero while ...
    direction: down # counting down at a ...
    tick_interval: 500ms # rate of once every half second
    debug: true
    control_events:
      - action: start # start when ...
        event: mode_bonus_started # the mode begins and ...
      - action: stop # stop when ...
        event: bonusDone # the mode is done

event_player:
  timer_bonusCountDown-tick{current_player.contracts==0}: # if the current player's contract value is zero ...
    - bonusDone # post the event bonusDone
  timer_bonusCountDown_tick{current_player.contracts>0}: # if the current player's contract value is greater than zero ...
    - bonusPayout # pay out and...
    - light_done  # post the event light_done

variable_player:
  timer_bonusCountDown_tick{current_player.contracts>0}:
    contracts: -1
    score: 1000 * (current_player.bonus_multiplier + 1)


#counters:
#  bonusStep:
#    count_events: s_popBumper_1_active
#    events_when_hit: light_done
#    starting_count: 3
#    count_complete_value: 0
#    direction: down
#    persist_state: false
#    disable_on_complete: true

show_player:
#  mode_bonus_started:
#    bonus_lighting:
#      speed: 1
  light_done{current_player.contracts==0}: # use the value of light_done to drive the shows
    1000_off:
      show_tokens:
        lights: l_bonus_1000
  light_done{current_player.contracts==1}:
    2000_off:
      show_tokens:
        lights: l_bonus_2000
  light_done{current_player.contracts==2}:
    3000_off:
      show_tokens:
        lights: l_bonus_3000
  light_done{current_player.contracts==3}:
    4000_off:
      show_tokens:
        lights: l_bonus_4000
  light_done{current_player.contracts==4}:
    5000_off:
      show_tokens:
        lights: l_bonus_5000
  light_done{current_player.contracts==5}:
    6000_off:
      show_tokens:
        lights: l_bonus_6000
  light_done{current_player.contracts==6}:
    7000_off:
      show_tokens:
        lights: l_bonus_7000
  light_done{current_player.contracts==7}:
    8000_off:
      show_tokens:
        lights: l_bonus_8000
  light_done{current_player.contracts==8}:
    9000_off:
      show_tokens:
        lights: l_bonus_9000
  light_done{current_player.contracts==9}:
    10000_off:
      show_tokens:
        lights: l_bonus_10000

#slide_player:
#  mode_bonus_started:
#  bonusPayout: bonusPayout_slide


#slides:
#  bonusPayout_slide:
#    type: text
#    text: Bonus Payout (contracts)
#    font_size: 25
#    color: blue
#    y: 75%
