#config_version=5

mode:
  stop_events: bonusDone # end when the last bonus is paid out

mode_settings:
  display_delay_ms: 1100ms
  bonus_entries:
    - event: bonusPayout
      score: 0 #1000 * (current_player.bonus_multiplier + 1)
      player_score_entry: current_player.contracts

timers:
  bonusCountDown:
    start_value: current_player.contracts # start with the current number of contracts collected and ...
    end_value: 0 # end at zero while ...
    direction: down # counting down at a ...
    tick_interval: 500ms # rate of once every half second
    debug: true
    control_events:
      - action: start # start when ...
        event: mode_bonus_started # the mode begins and ...
      - action: stop # stop when ...
        event: bonusDone # the mode is done

event_player:
  timer_bonusCountDown-tick{current_player.contracts==0}: # if the current player's contract value is zero ...
    - bonusDone # post the event bonusDone
  timer_bonusCountDown_tick{current_player.contracts>0}: # if the current player's contract value is greater than zero ...
    - bonusPayout # pay out and...
    - light_done  # post the event light_done

variable_player:
  timer_bonusCountDown_tick{current_player.contracts>0}:
    contracts: -1
    score: 1000 * (current_player.bonus_multiplier + 1)

sound_player:
  timer_bonusCountDown_tick: bonusPayout

show_player:
  light_done{current_player.contracts==0}: 1000_off # use the value of light_done to drive the shows
  light_done{current_player.contracts==1}: 2000_off
  light_done{current_player.contracts==2}: 3000_off
  light_done{current_player.contracts==3}: 4000_off
  light_done{current_player.contracts==4}: 5000_off
  light_done{current_player.contracts==5}: 6000_off
  light_done{current_player.contracts==6}: 7000_off
  light_done{current_player.contracts==7}: 8000_off
  light_done{current_player.contracts==8}: 9000_off
  light_done{current_player.contracts==9}: 10000_off

#slide_player:
#  mode_bonus_started:
#  bonusPayout: bonusPayout_slide


#slides:
#  bonusPayout_slide:
#    type: text
#    text: Bonus Payout (contracts)
#    font_size: 25
#    color: blue
#    y: 75%
