#config_version=5

mode:
  start_events: advance_perdition{count==3}
  stop_events: devil_bumper_hit
  priority: 170

shots:
  devil_bumper:
    switch: s_popBumper_3

show_player:
  mode_multiball_ready_started: flashDevil
