#config_version=5

#hardware:
#    platform: virtual_pinball

hardware:
    platform: opp # the playform is Open Pinball Platform
    driverboards: gen2

opp:
    ports: COM9, COM10 # these are the COM ports on the Cobrapin board
    chains:
        0: COM9 # the zero board is on COM 5 and the..
        1: COM10 # one board is on COM 6
    debug: True

modes: # for a mode to be seen by mpf it needs to be in this list otherwise it will be ignored
  - base
  - soulLanes
  - bonusEndOfBall
  - standUps
  - dash
  - dashLit
  - knockOut
  - inLanes
  - inLanesLit
  - outLanes
  - outLanesLit
  - cupSling
  - mugSling
  - perdition
  - perdition_multiball
  - multiball_fail
  - tilt
  - extraBall
  - high_score
  - star
  - zeroOut


psus:
  default:
    voltage: 35
    release_wait_ms: 100    # defaults to 10ms

player_vars: # these are player variables that can be seen by all modes
  bonus_multiplier:
    value_type: int
    initial_value: 1
  contracts:
    value_type: int
    initial_value: 0
  dice_pips:
    value_type: int
    initial_value: 0
  perdition_value:
    value_type: int
    initial_value: 0
  can_play:
    value_type: int
    initial_value: 1
  star_multiplier:
    value_type: int
    initial_value: 1
  flag:
    value_type: int
    initial_value: 0

counters:
  can_play:
    count_events: s_start_active
    starting_count: 0
    count_complete_value: 2
    direction: up
    events_when_hit: advance_can_play

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough # bd_plunger

config: # for a cleaner config file these have all been spit out to their own files
  - keyboard.yaml
  - hwSwitches.yaml
  - hwLights.yaml
  - hwCoils.yaml
  - sound.yaml

window: # defines the area of the TV monitor that can be used for the backbox display
  width: 540 # aspect ratio of the window ... set to 540 for small test window
  height: 650 # ... set to 650 for small test window
  title: CupheadWindow
  resizable: true
  fullscreen: false # does not take up the entire TV display and...
  borderless: true # has no "Windows 10" boarder around it
  exit_on_escape: true # lets you exit mpf and mpf-mc with hitting escape
  top: 0
  left: 0

displays: # VERY IMPORTANT these define three displays set into the "window"
  upper:
    width: 1080 # 1080 aspect ratios, all are full width
    height: 350
  middle:
    width: 1080
    height: 600
  lower:
    width: 1080
    height: 350
  window: # window itself must be included here so that the "layout" slide can be sent here
    width: 1080
    height: 1300

slides:
  layout: # THIS IS THE MAIN SLIDE THAT DRIVES ALL OF CUPHEADS BACKBOX!!!!
    widgets: # these widgets are the...
      - type: display # displays that are used to project slides for the backbox onto
        width: 1080 # aspect ration all are full width
        height: 350
        x: 0 # the display is set to the left of the window and the...
        y: 1300 # very top of the window with the...
        anchor_x: left # anchors set to the left...
        anchor_y: top # and top
        source_display: upper # the name of this display is UPPER
        #...........................................................
      - type: display
        width: 1080
        height: 600
        x: 0 # set to far left
        y: 950
        anchor_x: left
        anchor_y: top
        source_display: middle
        #...........................................................
      - type: display
        width: 1080
        height: 350
        x: 0 # set to far left
        y: 350
        anchor_x: left
        anchor_y: top
        source_display: lower
      - widget: player_added_widget

widgets:
  player_added_widget:
  - type: text
    text: PLAYER (can_play) ADDED!
    z: 110
    font_name: aafia
    font_size: 90
    anchor_y: bottom
    y: 375
    opacity: 0
    animations:
      player_added: contract_animation # this shows that animations declared in one mode are available in any mode

digital_score_reels:
  player_score:
    reel_count: 5
    include_player_number: true
    frames:
      - character: 0
        frame: 2
      - character: 1
        frame: 7
      - character: 2
        frame: 13
      - character: 3
        frame: 19
      - character: 4
        frame: 25
      - character: 5
        frame: 31
      - character: 6
        frame: 37
      - character: 7
        frame: 43
      - character: 8
        frame: 49
      - character: 9
        frame: 55


sound_player:
  player_added: stars

slide_player:
  mc_ready: # when the mc (Media Center) is ready start the...
    layout: # layout slide on the..
      target: window # ENTIRE Window

drop_targets: # this configs each switch to a drop target
  cup_C:
    switch: s_dt_C
  cup_U:
    switch: s_dt_U
  cup_P:
    switch: s_dt_P
  mug_M:
    switch: s_dt_M
  mug_U:
    switch: s_dt_U2
  mug_G:
    switch: s_dt_G

drop_target_banks: # this assigns the drop targets to their banks and sets parameters
  cup_bank:
    drop_targets: cup_C, cup_U, cup_P
    reset_coils: c_dt_reset_CUP
    reset_on_complete: 500ms
    reset_coil_max_wait_ms: 500ms
    reset_events: # reset the drop targets on these events
#      - drop_target_bank_cup_bank_down
      - resetCupAgain
      - ball_starting
      - machine_reset_phase_3
  mug_bank:
    drop_targets: mug_M, mug_U, mug_G
    reset_coils: c_dt_reset_MUG
    reset_on_complete: 500ms
    reset_coil_max_wait_ms: 500ms
    reset_events:
#      - drop_target_bank_mug_bank_down
      - resetMugAgain
      - ball_starting
      - machine_reset_phase_3

game: # sets game parameters
  balls_per_game: 2
  max_players: 2
