#config_version=5
hardware:
    platform: virtual_pinball
#hardware:
#    platform: opp
#    driverboards: gen2

#opp:
#    ports: COM3, COM4
#    chains:
#        0: COM4
#        1: COM3

modes: # for a mode to be seen by mpf it needs to be in this list otherwise it will be ignored
  - base
  - soulLanes
  - bonus
  - standUps
  - dashLit
  - knockOut
  - inLanes
  - outLanes
  - cupSling
  - mugSling
  - perdition
  - perdition_multiball
  - multiball_fail
  - tilt
  - extraBall

player_vars: #these are player variables that can be seen by all modes
  bonus_multiplier:
    value_type: int
    initial_value: 1

  contracts:
    value_type: int
    initial_value: 0
  dice_pips:
    value_type: int
    initial_value: 0
  perdition_value:
    value_type: int
    initial_value: 0

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough # bd_plunger

config: # for a cleaner config file these have all been spit out to their own files
  - keyboard.yaml
  - hwSwitches.yaml
  - hwLights.yaml
  - hwCoils.yaml
  - sound.yaml

window:
  width: 1080
  height: 1300
  title: CupheadWindow
  resizable: true
  fullscreen: false
  borderless: true
  exit_on_escape: true
  top: 0
  left: 0
    # source_display: widow

displays:
  window:
    width: 1080
    height: 1300
  upper:
    width: 1040
    height: 280
  middle:
    width: 1040
    height: 580
  lower:
    width: 1040
    height: 320
  overall:
    width: 1080
    height: 1300
  reel_display:
    width: 69
    height: 65

slides:
  layout:
    background_color: blue
    widgets:
      - type : display
        width: 69
        height: 65
        x: 60
        y: 200
        anchor_x: left
        anchor_y: top
        source_display: reel_display
      - type: display
        width: 1040
        height: 280
        x: 20
        y: 1270
        anchor_x: left
        anchor_y: top
        source_display: upper
      - type: display
        width: 1040
        height: 580
        x: 20
        y: 940
        anchor_x: left
        anchor_y: top
        source_display: middle
      - type: display
        width: 1040
        height: 320
        x: 20
        y: 340
        anchor_x: left
        anchor_y: top
        source_display: lower
      - type: display
        width: 1080
        height: 1300
        source_display: overall
  awesome_slide:
    widgets:
    - type: text
      text: Cuphead Pinball
      font_size: 50
    transition:
      type: push
      duration: 1s
      direction: left
  press_start:
    widgets:
    - type: Text
      text: PRESS START
      animations:
        pre_show_slide:
          - property: opacity
            value: 0
            duration: .5s
          - property: opacity
            value: 1
            duration: .5s
            repeat: false
    - type: Text
      text: FREE PLAY
      color: green
      y: 10
      anchor_y: bottom
    transition:
      type: move_in
      duration: 1s
      direction: right
  mission_pinball:
    widgets:
    - type: Text
      text: MISSION PINBALL
      color: red
    transition:
       type: move_in
       duration: 1s
       direction: top
  video_slide:
    - type: video
      video: playCHvideo
      end_behavior: stop
  last_game_score_slide:
    widgets:
    - type: text
      text: LAST GAME
      font_size: 50
      y: 60%
    - type: text
      text: (machine|player1_score)
      number_grouping: true
      min_digits: 2
      font_size: 50
      y: 40%
  logo_slide:
    opacity: .5
    widgets:
    - type: image
      image: logo
  reel_slide:
    widgets:
    - type: image
      image: reel
  background_slide:
    widgets:
    - type: image
      image: backdrop
  rotate_slide:
    widgets:
    - type: image
      image: rotate

slide_player:
  mc_ready:
    layout:
      target: window

drop_targets: # this configs each switch to a drop target
  cup_C:
    switch: s_dt_C
  cup_U:
    switch: s_dt_U
  cup_P:
    switch: s_dt_P
  mug_M:
    switch: s_dt_M
  mug_U:
    switch: s_dt_U2
  mug_G:
    switch: s_dt_G

drop_target_banks: # this assigns the drop targets to their banks and sets parameters
  cup_bank:
    drop_targets: cup_C, cup_U, cup_P
    reset_coils: c_dt_reset_CUP
    reset_on_complete: 500ms
    reset_events:
      - drop_target_bank_cup_bank_down
      - ball_starting
      - machine_reset_phase_3
  mug_bank:
    drop_targets: mug_M, mug_U, mug_G
    reset_coils: c_dt_reset_MUG
    reset_on_complete: 500ms
    reset_events:
      - drop_target_bank_mug_bank_down
      - ball_starting
      - machine_reset_phase_3

game:
  balls_per_game: 5
  max_players: 4


#videos:
#    CHvideo:
#    width: 100
#    height: 70
#    file: CHvideo.mp4


#event_player:
#  ball_starting:
#    cmd_drop_targets_reset
#    cmd_flippers_enable
#    cmd_autofire_coils_enable
#  tilt:
#    cmd_flippers_disable
#    cmd_autofire_coils_disable
#  ball_ending:
#    cmd_flippers_disable
#    cmd_autofire_coils_disable
