#config_version=5
hardware:
    platform: virtual_pinball
#hardware:
#    platform: opp # the playform is Open Pinball Platform
#    driverboards: gen2

#opp:
#    ports: COM3, COM4 # these are the COM ports on the Cobrapin board
#    chains:
#        0: COM4 # the zero board is on COM 4 and the..
#        1: COM3 # one board is on COM 3

modes: # for a mode to be seen by mpf it needs to be in this list otherwise it will be ignored
  - base
  - soulLanes
  - bonus
  - standUps
  - dashLit
  - knockOut
  - inLanes
  - outLanes
  - cupSling
  - mugSling
  - perdition
  - perdition_multiball
  - multiball_fail
  - tilt
  - extraBall

player_vars: # these are player variables that can be seen by all modes
  bonus_multiplier:
    value_type: int
    initial_value: 1
  contracts:
    value_type: int
    initial_value: 0
  dice_pips:
    value_type: int
    initial_value: 0
  perdition_value:
    value_type: int
    initial_value: 0

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough # bd_plunger

config: # for a cleaner config file these have all been spit out to their own files
  - keyboard.yaml
  - hwSwitches.yaml
  - hwLights.yaml
  - hwCoils.yaml
  - sound.yaml

window: # defines the area of the TV monitor that can be used for the backbox display
  width: 1080 # aspect ratio of the window
  height: 1300
  title: CupheadWindow
  resizable: true
  fullscreen: false # does not take up the entire TV display and...
  borderless: true # has no "Windows 10" boarder around it
  exit_on_escape: true # lets you exit mpf and mpf-mc with hitting escape
  top: 0
  left: 0

displays: # VERY IMPORTANT these define three displays set into the "window"
  upper:
    width: 1080 # aspect ratios, all are full width
    height: 350
  middle:
    width: 1080
    height: 600
  lower:
    width: 1080
    height: 350
  window: # window itself must be included here so that the "layout" slide can be sent here
    width: 1080
    height: 1300

slides:
  layout: # THIS IS THE MAIN SLIDE THAT DRIVES ALL OF CUPHEADS BACKBOX!!!!
    background_color: 000099 # sets the background color to a mif bright blue
    widgets: # these widgets are the...
      - type: display # displays that are used to project slides for the backbox onto
        width: 1080 # aspect ration all are full width but...
        height: 350 # partial height so they stack but not set to final heigh of 350 to show a
        # blue border under the slide,  This will change to 350 when Adrian gets up borders
        x: 0 # the display is set to the left of the window and the...
        y: 1300 # very top of the window with the...
        anchor_x: left # anchors set to the left...
        anchor_y: top # and top
        source_display: upper # the name of this display is UPPER
        #...........................................................
      - type: display
        width: 1080
        height: 600
        x: 0 # set to far left
        y: 950 # set to 950 because the top display will be 350 when the border is added
        anchor_x: left
        anchor_y: top
        source_display: middle
        #...........................................................
      - type: display
        width: 1080
        height: 350
        x: 0 # set to far left
        y: 350 # this will increas to 350 when the borders are added
        anchor_x: left
        anchor_y: top
        source_display: lower



slide_player:
  mc_ready: # when the mc (Media Center) is ready start the...
    layout: # layout slide on the..
      target: window # ENTIRE Window

drop_targets: # this configs each switch to a drop target
  cup_C:
    switch: s_dt_C
  cup_U:
    switch: s_dt_U
  cup_P:
    switch: s_dt_P
  mug_M:
    switch: s_dt_M
  mug_U:
    switch: s_dt_U2
  mug_G:
    switch: s_dt_G

drop_target_banks: # this assigns the drop targets to their banks and sets parameters
  cup_bank:
    drop_targets: cup_C, cup_U, cup_P
    reset_coils: c_dt_reset_CUP
    reset_on_complete: 500ms
    reset_events: # reset the drop targets on these events
      - drop_target_bank_cup_bank_down
      - ball_starting
      - machine_reset_phase_3
  mug_bank:
    drop_targets: mug_M, mug_U, mug_G
    reset_coils: c_dt_reset_MUG
    reset_on_complete: 500ms
    reset_events:
      - drop_target_bank_mug_bank_down
      - ball_starting
      - machine_reset_phase_3

game: # sets game parameters
  balls_per_game: 5
  max_players: 2


#videos:
#    CHvideo:
#    width: 100
#    height: 70
#    file: CHvideo.mp4


#event_player:
#  ball_starting:
#    cmd_drop_targets_reset
#    cmd_flippers_enable
#    cmd_autofire_coils_enable
#  tilt:
#    cmd_flippers_disable
#    cmd_autofire_coils_disable
#  ball_ending:
#    cmd_flippers_disable
#    cmd_autofire_coils_disable
