#config_version=5
#Cuphead Coils

coils:
  c_flipper_left_main:
    number: coil_1
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: coil_2
    allow_enable: true
  c_flipper_right_main:
    number: coil_3
    default_pulse_ms: 20
  c_flipper_right_hold:
    number: coil_4
    allow_enable: true
  c_trough_eject:
    number: coil_5
    default_pulse_ms: 20
  c_popBumper_1:
    number: coil_6
  c_popBumper_2:
    number: coil_7
  c_popBumper_3:
    number: coil_8
#  c_perdition:
#    number: coil9
  c_dash_L:
    number: coil_10
  c_dash_R:
    number: coil_11
  c_sling_L:
    number: coil_12
  c_sling_R:
    number: coil_13
  c_dt_reset_CUP:
    number: coil_14
    default_pulse_ms: 100  # 60 will work
  c_dt_reset_MUG:
    number: coil_15
    default_pulse_ms: 100  # 60 will work
  c_kicker:
    number: coil_16
  c_perdition_kicker:
    number: coil_17
  c_perdition_post_up:
    number: coil_18
    default_pulse_ms: 100
  c_perdition_post_down:
    number: coil_19
    default_pulse_ms: 100


autofire_coils:
  pop_bumper1:
    coil: c_popBumper_1
    switch: s_popBumper_1
  pop_bumper2:
    coil: c_popBumper_2
    switch: s_popBumper_2
  pop_bumper3:
    coil: c_popBumper_3
    switch: s_popBumper_3
  sling_L:
    coil: c_sling_L
    switch: s_sling_L
  sling_R:
    coil: c_sling_R
    switch: s_sling_R


flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: playfield
    entrance_count_delay: 300ms
    debug: true
  #bd_plunger:
  #  ball_switches: s_plunger
  #  entrance_count_delay: 300ms
  #  mechanical_eject: true
  bd_kicker:
    ball_switches: s_kicker
    eject_coil: c_kicker
    eject_targets: playfield
    eject_timeouts: 1S
  bd_perdition_kicker:
    ball_switches: s_perdition_kicker
    eject_coil: c_perdition_kicker
    eject_targets: playfield
    eject_timeouts: 1S
    eject_events: eject_bd_perdition_kicker
  bd_dash_L:
    ball_switches: s_dash_L
    eject_coil: c_dash_L
    eject_targets: playfield
    eject_timeouts: 1S
  bd_dash_R:
    ball_switches: s_dash_R
    eject_coil: c_dash_R
    eject_targets: playfield
    eject_timeouts: 1S
