#config_version=5
#Cuphead Lights

lights:

# Board 0 Chain 0    
  l_soul_L:
    number: 0-0-1
    type: grb
    subtype: led
    tags: soul_lanes
  l_soul_U:
    number: 0-0-2
    type: grb
    subtype: led
    tags: soul_lanes
  l_soul_O:
    number: 0-0-3
    type: grb
    subtype: led
    tags: soul_lanes
  l_soul_S:
    number: 0-0-4
    type: grb
    subtype: led
    tags: soul_lanes
  l_lane_L_1:
    number: 0-0-5
    type: grb
    subtype: led
    tags: lane_L
  l_lane_L_2:
    number: 0-0-6
    type: grb
    subtype: led
    tags: lane_L

  l_star_1:
    number: 0-0-7
    type: grb
    subtype: led
    tags: star

  l_lane_L_3:
    number: 0-0-8
    type: grb
    subtype: led
    tags: lane_L
  l_lane_L_4:
    number: 0-0-9
    type: grb
    subtype: led
    tags: lane_L

  l_star_2:
    number: 0-0-10
    type: grb
    subtype: led
    tags: star

  l_lane_L_5:
    number: 0-0-11
    type: grb
    subtype: led
    tags: lane_L
  l_lane_L_6:
    number: 0-0-12
    type: grb
    subtype: led
    tags: lane_L

  l_dash_L:
    number: 0-0-13
    type: grb
    subtype: led
    tags: dash
  l_outLane_L:
    number: 0-0-14
    type: grb
    subtype: led
    tags: outLanes
  l_inLane_L:
    number: 0-0-15
    type: grb
    subtype: led
    tags: inLanes
  l_cup_sling:
    number: 0-0-16
    type: grb
    subtype: led

 
  l_bonus_5000:
    number: 0-0-17
    type: grb
    subtype: led
    tags: bonus
  l_bonus_4000:
    number: 0-0-18
    type: grb
    subtype: led
    tags: bonus
  l_bonus_3000:
    number: 0-0-19
    type: grb
    subtype: led
    tags: bonus
  l_bonus_2000:
    number: 0-0-20
    type: grb
    subtype: led
    tags: bonus
  l_bonus_1000:
    number: 0-0-21
    type: grb
    subtype: led
    tags: bonus

  l_shootAgain:
    number: 0-0-22
    type: grb
    subtype: led

 l_bonus_6000:
    number: 0-0-23
    type: grb
    subtype: led
    tags: bonus
  l_bonus_7000:
    number: 0-0-24
    type: grb
    subtype: led
    tags: bonus
  l_bonus_8000:
    number: 0-0-25
    type: grb
    subtype: led
    tags: bonus

  l_2x:
    number: 0-0-26
    type: grb
    subtype: led
  l_3x:
    number: 0-0-27
    type: grb
    subtype: led
  l_4x:
    number: 0-0-28
    type: grb
    subtype: led


  l_dice:
    number: 0-0-29
    type: grb
    subtype: led

  l_bonus_10000:
    number: 0-0-30
    type: grb
    subtype: led
    tags: bonus
  l_bonus_9000:
    number: 0-0-31
    type: grb
    subtype: led
    tags: bonus

  l_mug_sling:
    number: 0-0-32
    type: grb
    subtype: led

  l_inLane_R:
    number: 0-0-33
    type: grb
    subtype: led
    tags: inLanes
  l_outLane_R:
    number: 0-0-34
    type: grb
    subtype: led
    tags: outLanes

  l_dash_R:
    number: 0-0-35
    type: grb
    subtype: led
    tags: dash

  l_star_3:
    number: 0-0-36
    type: grb
    subtype: led
    tags: star

  l_perdition_1:
    number: 0-0-37
    type: grb
    subtype: led
    tags: perdition
  l_perdition_2:
    number: 0-0-38
    type: grb
    subtype: led
    tags: Pperdition
  l_perdition_3:
    number: 0-0-39
    type: grb
    subtype: led
    tags: perdition

  l_extraBall:
    number: 0-0-40
    type: grb
    subtype: led

  l_popBumper_2:
    number: 0-0-41
    type: grb
    subtype: led
    tags: popBumper
  l_popBumper_3:
    number: 0-0-42
    type: grb
    subtype: led
    tags: popBumper
  l_popBumper_1:
    number: 0-0-43
    type: grb
    subtype: led
    tags: popBumper

  l_standUp_1:
    number: 0-0-44
    type: grb
    subtype: led
    tags: standUp
  l_standUp_2:
    number: 0-0-45
    type: grb
    subtype: led
    tags: standUp
  l_standUp_3:
    number: 0-0-46
    type: grb
    subtype: led
    tags: standUp

  l_special7:
    number: 0-0-47
    type: grb
    subtype: led

#  l_blueShooter:
 #   number: 0-0-41
  #  type: grb
   # subtype: led

# Board 1 Chain 1
  l_gi1:
    number: 1-0-1
    subtype: led
    tags: gi
  l_gi2:
    number: 1-0-2
    subtype: led
    tags: gi
  l_gi3:
    number: 1-0-3
    subtype: led
    tags: gi
  l_gi4:
    number: 1-0-4
    subtype: led
    tags: gi
  l_gi5:
    number: 1-0-5
    subtype: led
    tags: gi
  l_gi6:
    number: 1-0-6
    subtype: led
    tags: gi
  l_gi7:
    number: 1-0-7
    subtype: led
    tags: gi
  l_gi8:
    number: 1-0-8
    subtype: led
    tags: gi
  l_gi9:
    number: 1-0-9
    subtype: led
    tags: gi
  l_gi10:
    number: 1-0-10
    subtype: led
    tags: gi
  l_gi11:
    number: 1-0-11
    subtype: led
    tags: gi
  l_gi12:
    number: 1-0-12
    subtype: led
    tags: gi
  l_gi13:
    number: 1-0-13
    subtype: led
    tags: gi
  l_gi14:
    number: 1-0-14
    subtype: led
    tags: gi
  l_gi15:
    number: 1-0-15
    subtype: led
    tags: gi
  l_gi16:
    number: 1-0-16
    subtype: led
    tags: gi
  l_gi17:
    number: 1-0-17
    subtype: led
    tags: gi
  l_gi18:
    number: 1-0-18
    subtype: led
    tags: gi
  l_gi19:
    number: 1-0-19
    subtype: led
    tags: gi
  l_gi20:
    number: 1-0-20
    subtype: led
    tags: gi
  l_gi21:
    number: 1-0-21
    subtype: led
    tags: gi
  l_gi22:
    number: 1-0-22
    subtype: led
    tags: gi
  l_gi23:
    number: 1-0-23
    subtype: led
    tags: gi
  l_gi24:
    number: 1-0-24
    subtype: led
    tags: gi
  l_gi25:
    number: 1-0-25
    subtype: led
    tags: gi
  l_gi26:
    number: 1-0-26
    subtype: led
    tags: gi
  l_gi27:
    number: 1-0-27
    subtype: led
    tags: gi
  l_gi28:
    number: 1-0-28
    subtype: led
    tags: gi
  l_gi29:
    number: 1-0-29
    subtype: led
    tags: gi
  l_gi30:
    number: 1-0-30
    subtype: led
    tags: gi
  l_gi31:
    number: 1-0-31
    subtype: led
    tags: gi

