#config_version=5
# Cuphead Switches

machine:
  balls_installed: 5
  min_balls: 1

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2

switches:
  s_left_flipper:
    number: 0-0-1
    tags: left_flipper
  s_right_flipper:
    number: 1-0-1
    tags: right_flipper
  s_trough1:
    number: 0-0-32
    tags: trough
  s_trough2:
    number: 0-0-33
    tags: trough
  s_trough_jam:
    number: 0-0-34
    tags: trough
  s_start:
    number: 0-0-3
    tags: start
  s_popBumper_1:
    number: 0-0-8
    tags: popBumperSw
  s_popBumper_2:
    number: 0-0-9
    tags: popBumperSw
  s_popBumper_3:
    number: 0-0-10
    tags: popBumperSw
  s_soul_S:
    number: 0-0-56
    tags: inLanesSw
  s_soul_O:
    number: 0-0-57
    tags: inLanesSw
  s_soul_U:
    number: 0-0-58
    tags: inLanesSw
  s_soul_L:
    number: 0-0-59
    tags: inLanesSw
  s_standUp_1:
    number: 0-0-11
    tags: standUp_LSw
  s_standUp_2:
    number: 0-0-1
    tags: standUp_LSw
  s_standUp_3:
    number: 1-0-2
    tags: standUp_LSw
  s_standUp_R:
    number: 1-0-3
  s_star_2:
    number: 0-0-53
    tags: starSw
  s_star_3:
    number: 0-0-45
    tags: starSw
  s_kicker:
    number: 0-0-44
  s_perdition:
    number: 0-0-43
    tags: playfield_active
  s_dt_C:
    number: 0-0-50
    tags: dtSw
  s_dt_U:
    number: 0-0-51
    tags: dtSw
  s_dt_P:
    number: 0-0-52
    tags: dtSw
  s_dt_M:
    number: 0-0-40
    tags: dtSw
  s_dt_U2:
    number: 0-0-41
    tags: dtSw
  s_dt_G:
    number: 0-0-42
    tags: dtSw
  s_dtSling_L:
    number: 1-0-8
    tags: dtSlingSw
  s_dtSling_R:
    number: 1-0-9
    tags: dtSlingSw
  s_dash_L:
    number: 0-0-10
    tags: dashSw
  s_dash_R:
    number: 0-0-11
    tags: dashSw
  s_midRight:
    number: 0-0-37
  s_outLane_L:
    number: 0-0-49
    tags: bottomLanesSw
  s_inLane_L:
    number: 0-0-48
    tags: bottomLanesSw
  s_outLane_R:
    number: 0-0-35
    tags: bottomLanesSw
  s_inLane_R:
    number: 0-0-36
    tags: bottomLanesSw
  s_perdition_kicker:
    number: 0-0-60
  s_perdition_lane:
    number: 0-0-61
  s_sling_L:
    number: 1-0-16 ####
    tags: slingSw
  s_sling_R:
    number: 1-0-17 ####
    tags: slingSw
  s_star_1:
    number: 1-0-18 #####
    tags: starSw
  s_tilt_bob:
    number: 1-0-27 ####18
    tags: tilt_warning
  s_spinner:
    number: 1-0-26 ####19
  s_ball_tilt:
    number: 1-0-24  ####20
  s_slam_tilt:
    number: 1-0-25  ####21
