#config_version=5

machine:
  balls_installed: 5
  min_balls: 1

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2

switches:
  # Board 0 Chain 0
  s_left_flipper:
    number: 1-0-11
    tags: left_flipper
  s_start:
    number: 1-0-2
    tags: start
  s_tilt_bob:
    number: 1-0-3
    tags: tilt_warning
  s_ball_tilt:
    number: 1-0-9

  s_right_flipper:
    number: 1-0-10
    tags: right_flipper

  s_dt_M:
    number: 0-0-16
    tags: dtSw
    type: 'NC'
  s_dt_G:
    number: 0-0-17
    tags: dtSw
    type: 'NC'
  s_dtSling_L:
    number: 0-0-18
    tags: dtSlingSw, playfield_active
  s_dtSling_R:
    number: 0-0-19
    tags: dtSlingSw, playfield_active
  s_popBumper_1:
    number: 0-0-24
    tags: popBumperSw
  s_popBumper_2:
    number: 0-0-25
    tags: popBumperSw
  s_popBumper_3:
    number: 0-0-26
    tags: popBumperSw
  s_dt_U2:
    number: 0-0-27
    tags: dtSw
    type: 'NC'

  # Board 1 Chain 1
  s_dt_U:
    number: 0-0-1
    tags: dtSw
    type: 'NC'
  s_dt_P:
    number: 0-0-2
    tags: dtSw
    type: 'NC'
  s_dt_C:
    number: 0-0-3
    tags: dtSw
    type: 'NC'
  s_EOS_L:
    number: 0-0-8
    type: 'NC'

  s_sling_L:
    number: 0-0-9
    tags: slingSw
  s_EOS_R:
    number: 0-0-10
    type: 'NC'

  s_sling_R:
    number: 0-0-11
    tags: slingSw

  # Board 1 Switch Matrix (4x6)
  # Column 1
  s_trough1:
    number: 1-0-32
    tags: trough
#    type: 'NC'
  s_trough2:
    number: 1-0-33
    tags: trough
    type: 'NC'
  s_trough_jam:
    number: 1-0-34
    tags: trough
#    type: 'NC'
  s_outLane_R:
    number: 1-0-35
    tags: bottomLanesSw
    type: 'NC'
  s_inLane_R:
    number: 1-0-39
    tags: bottomLanesSw
    type: 'NC'

  # Column 2
  # 1-0-40 is empty
  s_midRight:
    number: 1-0-40
    tags: playfield_active
    type: 'NC'
  s_star_3:
    number: 1-0-41
    tags: starSw, playfield_active
    type: 'NC'
  s_soul_L:
    number: 1-0-42
    tags: inLanesSw
    type: 'NC'
  s_kicker:
    number: 1-0-43
    type: 'NC'
  s_standUp_R:
    number: 1-0-47
    type: 'NC'
  s_standUp_3:
    number: 1-0-45
    tags: standUp_LSw
    type: 'NC'
  s_dash_R:
    number: 1-0-46
    type: 'NC'
    tags: dashSw


  # Column 3
  s_inLane_L:
    number: 1-0-48
    tags: bottomLanesSw
    type: 'NC'
  s_outLane_L:
    number: 1-0-49
    tags: bottomLanesSw
    type: 'NC'
  s_soul_S:
    number: 1-0-50
    tags: inLanesSw
    type: 'NC'
  s_star_2:
    number: 1-0-51
    tags: starSw, playfield_active
    type: 'NC'
  s_star_1:
    number: 1-0-55
    tags: starSw, playfield_active
    type: 'NC'
  s_standUp_2:
    number: 1-0-53
    tags: standUp_LSw
    type: 'NC'
  s_spinner:
    number: 1-0-54
    tags: playfield_active
    type: 'NC'



  # Column 4
  s_shooter_lane:
    number: 1-0-56
    tags: playfield_active
    type: 'NC'
  s_perdition_lane:
    number: 1-0-57
    tags: playfield_active
    type: 'NC'
  s_soul_U:
    number: 1-0-58
    tags: inLanesSw
    type: 'NC'
  s_soul_O:
    number: 1-0-59
    tags: inLanesSw
    type: 'NC'
  s_perdition_kicker:
    number: 1-0-63
    type: 'NC'
    ignore_window_ms: 300 # this will prevent multiple hits to the switch for more accurate counting
  s_standUp_1:
    number: 1-0-61
    tags: standUp_LSw
    type: 'NC'
  s_dash_L:
    number: 1-0-62
    tags: dashSw
    type: 'NC'
































    #
