#config_version=5

machine:
  balls_installed: 5
  min_balls: 1

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2

switches:
  # Board 0 Chain 0
  s_left_flipper:
    number: 0-0-1
    tags: left_flipper
  s_start:
    number: 0-0-2
    tags: start
  s_tilt_bob:
    number: 0-0-3
    tags: tilt_warning
  s_ball_tilt:
    number: 0-0-8
  s_slam_tilt:
    number: 0-0-9
  s_right_flipper:
    number: 0-0-10
    tags: right_flipper

  s_dash_L:
    number: 0-0-16
    tags: dashSw
  s_dash_R:
    number: 0-0-17
    tags: dashSw
  s_dtSling_L:
    number: 0-0-18
    tags: dtSlingSw
  s_dtSling_R:
    number: 0-0-19
    tags: dtSlingSw
  s_popBumper_1:
    number: 0-0-24
    tags: popBumperSw
  s_popBumper_2:
    number: 0-0-25
    tags: popBumperSw
  s_popBumper_3:
    number: 0-0-26
    tags: popBumperSw

  # Board 1 Chain 1
  s_standUp_1:
    number: 1-0-1
    tags: standUp_LSw
  s_standUp_2:
    number: 1-0-2
    tags: standUp_LSw
  s_standUp_3:
    number: 1-0-3
    tags: standUp_LSw
  s_standUp_R:
    number: 1-0-8
  s_sling_L:
    number: 1-0-9
    tags: slingSw
  s_sling_R:
    number: 1-0-10
    tags: slingSw

  # Board 1 Switch Matrix (4x6)
  # Column 1
  s_trough1:
    number: 1-0-32
    tags: trough
  s_trough2:
    number: 1-0-33
    tags: trough
  s_trough_jam:
    number: 1-0-34
    tags: trough
  s_outLane_R:
    number: 1-0-35
    tags: bottomLanesSw
  s_inLane_R:
    number: 1-0-36
    tags: bottomLanesSw
  s_midRight:
    number: 1-0-37
  s_spinner:
    number: 1-0-38

  # Column 2
  s_dt_M:
    number: 1-0-40
    tags: dtSw
  s_dt_U2:
    number: 1-0-41
    tags: dtSw
  s_dt_G:
    number: 1-0-42
    tags: dtSw
  s_perdition:
    number: 1-0-43
    tags: playfield_active
  s_kicker:
    number: 1-0-44
  s_star_3:
    number: 1-0-45
    tags: starSw
  s_perdition_kicker:
    number: 1-0-46

  # Column 3
  s_inLane_L:
    number: 1-0-48
    tags: bottomLanesSw
  s_outLane_L:
    number: 1-0-49
    tags: bottomLanesSw
  s_dt_C:
    number: 1-0-50
    tags: dtSw
  s_dt_U:
    number: 1-0-51
    tags: dtSw
  s_dt_P:
    number: 1-0-52
    tags: dtSw
  s_star_2:
    number: 1-0-53
    tags: starSw
  s_star_1:
    number: 1-0-54
    tags: starSw

  # Column 4
  s_soul_S:
    number: 1-0-56
    tags: inLanesSw
  s_soul_O:
    number: 1-0-57
    tags: inLanesSw
  s_soul_U:
    number: 1-0-58
    tags: inLanesSw
  s_soul_L:
    number: 1-0-59
    tags: inLanesSw
  s_perdition_kicker:
    number: 1-0-60
  s_perdition_lane:
    number: 1-0-61
  s_shooter_lane:
    number: 1-0-62


























    #
