#config_version=5
# Cuphead Switches

machine:
  balls_installed: 5
  min_balls: 1

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2

switches:
  s_left_flipper:
    number: 0
    tags: left_flipper
  s_right_flipper:
    number: 1
    tags: right_flipper
  s_trough1:
    number: 2
    tags: trough
  s_trough2:
    number: 3
    tags: trough
  s_trough_jam:
    number: 4
    tags: trough
  s_plunger:
    number: 5
  s_start:
    number: 6
    tags: start
  s_exit_shooter_lane:
    number: 7
    tags: playfield_active
  s_popBumper_1:
    number: 8
    tags: popBumperSw
  s_popBumper_2:
    number: 9
    tags: popBumperSw
  s_popBumper_3:
    number: 10
    tags: popBumperSw
  s_soul_S:
    number: 11
    tags: inLanesSw
  s_soul_O:
    number: 12
    tags: inLanesSw
  s_soul_U:
    number: 13
    tags: inLanesSw
  s_soul_L:
    number: 14
    tags: inLanesSw
  s_standUp_1:
    number: 15
    tags: standUp_LSw
  s_standUp_2:
    number: 16
    tags: standUp_LSw
  s_standUp_3:
    number: 17
    tags: standUp_LSw
  s_standUp_R:
    number: 18
  s_star_1:
    number: 19
    tags: starSw
  s_star_2:
    number: 20
    tags: starSw
  s_star_3:
    number: 21
    tags: starSw
  s_kicker:
    number: 22
  s_perdition:
    number: 23
    tags: playfield_active
  s_dt_C:
    number: 24
    tags: dtSw
  s_dt_U:
    number: 25
    tags: dtSw
  s_dt_P:
    number: 26
    tags: dtSw
  s_dt_M:
    number: 27
    tags: dtSw
  s_dt_U2:
    number: 28
    tags: dtSw
  s_dt_G:
    number: 29
    tags: dtSw
  s_dtSling_L:
    number: 30
    tags: dtSlingSw
  s_dtSling_R:
    number: 31
    tags: dtSlingSw
  s_dash_L:
    number: 32
    tags: dashSw
  s_dash_R:
    number: 33
    tags: dashSw
  s_midRight:
    number: 34
  s_sling_L:
    number: 35
    tags: slingSw
  s_sling_R:
    number: 36
    tags: slingSw
  s_outLane_L:
    number: 37
    tags: bottomLanesSw
  s_inLane_L:
    number: 38
    tags: bottomLanesSw
  s_outLane_R:
    number: 39
    tags: bottomLanesSw
  s_inLane_R:
    number: 40
    tags: bottomLanesSw
  s_tilt:
    number: 41
    tags: tilt
  s_coin:
    number: 42
  s_perdition_kicker:
    number: 43
  s_spinner:
    number: 44
