#config_version=5
# Cuphead
keyboard:
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  p:
    switch: s_plunger
    toggle: true
  g:
    switch: s_trough2
    toggle: true
  h:
    switch: s_trough1
    toggle: true
  1:
    switch: s_start
  q:
    switch: s_popBumper_1
  w:
    switch: s_popBumper_2
  e:
    switch: s_popBumper_3
  t:
    switch: s_tilt
  2:
    switch: s_dt_C
  3:
    switch: s_dt_U
  4:
    switch: s_dt_P
  5:
    switch: s_dt_M
  6:
    switch: s_dt_U2
  7:
    switch: s_dt_G
  i:
    switch: s_spinner
  s:
    switch: s_soul_S
  o:
    switch: s_soul_O
  u:
    switch: s_soul_U
  l:
    switch: s_soul_L
  d:
    switch: s_dash_L
  a:
    switch: s_dash_R
