#config_version=5
# Cuphead
keyboard:
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  p:
    switch: s_plunger
    toggle: true
  g:
    switch: s_trough2
    toggle: true
  h:
    switch: s_trough1
    toggle: true
  s:
    switch: s_start
  a:
    switch: s_exit_shooter_lane
  q:
    switch: s_popBumper_1
  w:
    switch: s_popBumper_2
  e:
    switch: s_popBumper_3
  t:
    switch: s_tilt
  c:
    switch: s_coin
  i:
    switch: s_spinner
  0:
    switch: reel0
  1:
    switch: reel1
  2:
    switch: reel2
  3:
    switch: reel3
  4:
    switch: reel4
  5:
    switch: reel5
  6:
    switch: reel6
  7:
    switch: reel7
  8:
    switch: reel8
  9:
    switch: reel9
