#config_version=5

mode:
  start_events: ball_starting #, multiball_perdition_multiball_ball_lost # starts along side basae mode
  priority: 210
#  stop_events: startMBPost #ball_ended, #ends on ball drained or multiball achieved (devil bumper)

counters:
  perdition_entry:
    count_events: s_perdition_kicker_active, startMBPost #, eject_bd_perdition_kicker # increments every time the perdition kicker fires and ...
    count_complete_value: 4 # is complete after three entries into berdition and then exit...
    starting_count: 0 # startes at zero
    direction: up #  It counts up and ...
    persist_state: true # keeps it's count from ball to ball
    events_when_hit: advance_perdition  # It posts advance_perdition when incremented and ...
    reset_on_complete: true # resets upon completion and ...
    disable_on_complete: false # will start up again after completion

show_player:
  advance_perdition{count==1}: perdition1on # first time show this
  advance_perdition{count==2}: perdition2on
  advance_perdition{count==3}: perdition3on, flashDevil
  startMBPost: giOn

sequences:
  multiballReady:
    events:
      - advance_perdition{count==3}
  #    - s_perdition_kicker_active
    events_when_complete: mbReady
    reset_on_complete: True
  startMB:
    events:
      - advance_perdition{count==3}
      - s_popBumper_2_active
    events_when_complete: startMBPost
    reset_on_complete: True

shots:
  perdition_lane:
    switch: s_perdition_kicker
    profile: perdition_lane_profile

shot_profiles:
  perdition_lane_profile:
    states:
      - name: initialState
        show: perdition0
      - name: firstEntry
        show: perdition1on
      - name: secondEntry
        show: perdition2on
      - name: thirdEntry
        show: perdition3on
    loop: True

variable_player:
  s_perdition_kicker_active:
    score: 100
  advance_perdition{count==1}: # Upon the event "advance_perdition" if the player's perdition value is 1 then ...
    perdition_value: 1
  advance_perdition{count==2}:
    perdition_value: 1
  advance_perdition{count==3}:
    perdition_value: 1
#  advance_perdition{count==3}:


sound_player:
  advance_perdition{count==1}: perdition
  advance_perdition{count==2}: perdition
  advance_perdition{count==3}: perditionLock
