#config_version=5

mode:
  start_events: ball_starting, multiball_perdition_multiball_ball_lost # starts along side basae mode
  priority: 210
  stop_events: devil_bumper_hit, ball_ended #ends on ball drained or multiball achieved (devil bumper)

counters:
  perdition_entry:
    count_events: s_perdition_kicker_active # increments every time the perdition kicker fires and ...
    count_complete_value: 3 # is complete after three entries into berdition and ...
    starting_count: 0 # startes at zero
    direction: up #  It counts up and ...
    persist_state: true # keeps it's count from ball to ball
    events_when_hit: advance_perdition  # It posts advance_perdition when incremented and ...
    reset_on_complete: true # resets upon completion and ...
    disable_on_complete: false # will start up again after completion

show_player:
  advance_perdition{count==1}: perdition1on # first time show this
  advance_perdition{count==2}: perdition2on
  advance_perdition{count==3}: perdition3on

shots:
  perdition_lane:
    switch: s_perdition_kicker
    profile: perdition_lane_profile

shot_profiles:
  perdition_lane_profile:
    states:
      - name: initialState
        show: perdition0
      - name: firstEntry
        show: perdition1on
      - name: secondEntry
        show: perdition2on
      - name: thirdEntry
        show: perdition3on

variable_player:
  s_perdition_kicker_active:
    score: 100
  advance_perdition{current_player.perdition_value==0}: # Upon the event "advance_perdition" if the player's perdition value is 0 then ...
    perdition_value: 1 # increment it by one
  advance_perdition{current_player.perdition_value==1}:
    perdition_value: 1
  advance_perdition{current_player.perdition_value==2}:
    perdition_value: 1
  advance_perdition{current_player.perdition_value==3}:
    perdition_value: 1

sound_player:
  advance_perdition{count==1}: perdition
  advance_perdition{count==2}: perdition
  advance_perdition{count==3}: perditionLock
