#config_version=5

mode:
  start_events: ball_starting, multiball_perdition_multiball_ball_lost
  priority: 210
  stop_events: devil_bumper_hit, ball_ended


counters:
  perdition_entry:
    count_events: s_perdition_kicker_active
    count_complete_value: 3
    starting_count: 0
    direction: up
    persist_state: true
    events_when_hit: advance_perdition
    reset_on_complete: true
    disable_on_complete: false

show_player:
  advance_perdition{count==1}: perdition1on
  advance_perdition{count==2}: perdition2on
  advance_perdition{count==3}: perdition3on

variable_player:
  s_perdition_kicker_active:
    score: 100
  advance_perdition{current_player.perdition_value==3}:
    perdition_value:
      int: 1
  advance_perdition{current_player.perdition_value==2}:
    perdition_value: 1
  advance_perdition{current_player.perdition_value==1}:
    perdition_value: 1
  advance_perdition{current_player.perdition_value==0}:
    perdition_value: 1
