#config_version=5

tilt:
  tilt_warning_switch_tag: tilt_warning
  warnings_to_tilt: 3
  reset_warnings_events: ball_started
  settle_time: 5s
  multiple_hit_window: 1500ms


#widgets:
#  tilt_warning_1_widget:
#    - type: text
#      text: YIKES!
#      font_name: Aafia
#      font_size: 100
#      color: red
#      animations:
#        tilt_warning_1: contract_animation
#  tilt_warning_2_widget:
#    - type: text
#      text: YIKES!
#      font_name: Aafia
#      font_size: 100
#      color: red
#      animations:
#        tilt_warning_2: contract_animation
#  tilt_widget:
#    - type: text
#      text: TILT!
#      font_name: Aafia
#      font_size: 100
#      color: red
#      animations:
#        tilt: contract_animation

slides:
  _overwrite: true   # this is important to overwrite the existing slides
  tilt_warning_1:
    widgets:
      - type: text
        text: YIKES!
        font_name: Aafia
        color: red
        font_size: 100
    expire: 1s
  tilt_warning_2:
    widgets:
      - type: text
        text: YOWZA!
        font_name: Aafia
        color: red
        font_size: 100
    expire: 1S
  tilt:
    widgets:
      - type: text
        text: NOW YOU'VE DONE IT!
        font_name: Aafia
        color: red
        font_size: 100
        opacity: 0
    expire: 2s

slide_player:
  tilt_warning_1:
    tilt_warning_1:
      target: middle
  tilt_warning_2:
    tilt_warning_2:
      target: middle
  tilt:
    tilt:
      target: upper
  tilt_clear:
    tilt:
      action: remove

sound_player:
  tilt_warning_1: perditionLock
  tilt_warning_2: perditionLock
  tilt: perditionLock
