#config_version=5

tilt:
  tilt_warning_switch_tag: tilt_warning
  warnings_to_tilt: 3
  reset_warnings_events: ball_started
  settle_time: 5s
  multiple_hit_window: 1500ms


widgets:
  tilt_warning_1_widget:
    - type: text
      text: YIKES!
      font_name: Aafia
      font_size: 100
      font_color: red
      animations:
        tilt_warning_1: contract
  tilt_warning_2_widget:
    - type: text
      text: YIKES!
      font_name: Aafia
      font_size: 100
      font_color: red
      animations:
        tilt_warning_2: contract
  tilt_widget:
    - type: text
      text: TILT!
      font_name: Aafia
      font_size: 100
      font_color: red 
      animations:
        tilt: contract

slides:
  _overwrite: true   # this is important to overwrite the existing slides
#  tilt_warning_1:
#    widgets:
#      - type: text
#        text: YIKES!
#        font_name: Aafia
#        color: red
#        font_size: 100
#    expire: 1s
#    source_display: upper
#  tilt_warning_2:
#    widgets:
#      - type: text
#        text: YIKES!
#        font_name: Aafia
#        color: red
#        font_size: 100
#    expire: 1s
#    source_display: lower
#  tilt:
#    widgets:
#      - type: text
#        text: TILT!
#        font_name: Aafia
#        color: red
#        font_size: 100
#        z: 900
#        opacity: 0
#    expire: 2s
#    source_display: middle
