#config_version=5

tilt:
  tilt_warning_switch_tag: tilt_warning
  warnings_to_tilt: 3
  reset_warnings_events: ball_started
  settle_time: 5s
  multiple_hit_window: 1500ms

slide_player:
  _overwrite: true
  tilt_warning_1: tilt_warning
  tilt_warning_2: tilt_warning_2
  tilt: tilt_slide
  tilt_clear:
    tilt_slide:
         action: remove

slides:
  tilt_warning:
    widgets:
      - type: text
        text: YIKES!
        font_name: Aafia
        color: red
        font_size: 100
    expire: 2s
  tilt_warning_2:
    widgets:
      - type: text
        text: YIKES!
        font_name: Aafia
        color: red
        font_size: 100
    expire: 2s
  tilt_slide:
    widgets:
      - type: text
        text: TILT
        font_name: Aafia
        color: red
        font_size: 100
