#config_version=5

mode:
  start_events:
    - ball_started
    - resetLitOutLanes
  priority: 150
  stop_events: rightStar_complete

variable_player:
  s_outLane_L_active:
    score: 100
  s_outLane_R_active:
    score: 100
