#config_version=5

mode:
  start_events: timer_perditionPost_timer_complete
  stop_events:  s_trough1_active{current_player.perditionBallSaveOn==0}
  priority: 210
  restart_on_next_ball: true

timers:
  settle_timer:
    direction: down
    start_value: 4
    end_value: 0
    tick_interval: 100ms
    debug: true
    control_events:
      - action: start
        event: s_perdition_kicker_active.2
      - action: restart
        event: s_perdition_kicker_active.3

variable_player:
  s_perdition_kicker_active:
    perdition_value:
      int: 0
      action: set
    advance_perdition_value:
      int: 0
      action: set

event_player:
  s_perdition_kicker_active: clearLane

coil_player:
  clearLane: c_perdition_post_down
  timer_settle_timer_complete: c_perdition_kicker

show_player:
  s_perdition_kicker_active:
    perdition0: play
    perdition1on: stop
    perdition2on: stop
    perdition3On: stop
